- name: Demo Play 1
  hosts: localhost
  vars:
    URL: play.exmmple.com 
  tasks:
    - name: print Hello
      ansible.builtin.debug:
       msg: URL = {{ URL }}



- name: play variable from files 
  hosts: localhost
  vars_files:
    - var.yml
  tasks:
    - name: print play variable from file
      ansible.builtin.debug:
       msg: URL = {{ URL }}
