- name: Demo Play 1
  hosts: localhost
  vars:
    URL: play.exmmple.com 
  tasks:
    - name: print Hello
      ansible.builtin.debug:
       msg: URL = {{ URL }}



- name: play variable from files 
  hosts: localhost
  #vars_files works only under play level
  vars_files:
    - var.yml
  tasks:
    - name: print play variable from file
      ansible.builtin.debug:
       msg: URL = {{ URL }}


- name: Task level variable from files 
  hosts: localhost
  tasks:
    - name: print play variable from file
      vars:
        URL: task.explame.com
      ansible.builtin.debug:
        msg: URL = {{ URL }}
     


- name: variable  from  INV  
  hosts: all
  tasks:
    - name: print play variable from INV
      ansible.builtin.debug:
        msg: URL = {{ URL }}
      